<?php

namespace App\Repository;

/**
 * AccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccessRepository extends \Doctrine\ORM\EntityRepository
{
     
    public function __construct(\Doctrine\ORM\EntityManagerInterface $em, \Doctrine\ORM\Mapping\ClassMetadata $metaData = null) {
        parent::__construct($em, $metaData == null ? 
                new \Doctrine\ORM\Mapping\ClassMetadata(\App\Entity\Access::class) : $metaData);
    }
}
